import {StyleSheet} from 'react-native';
import {colors, rfs, rhp, wp, rwp} from '../../../constants';
import fonts from '../../../constants/fonts';

const styles = StyleSheet.create({
  infoContainerStyle: {alignItems: 'center', paddingVertical: 15, flex: 1},
  nameContainerStyle: {flexDirection: 'row'},
  infoTextStyle: {
    fontFamily: fonts.SF_PRO_TEXT.Poppins.Light,
    fontWeight: '500',
    fontSize: rfs(14),
    lineHeight: rhp(17),
    color: colors.GRAY.textLightGray,
    marginRight: rwp(4),
  },
  dummy: {
    backgroundColor: 'red',
  },
  container: {
    flex: 1,
    backgroundColor: colors.GREEN.primaryGreen,
  },
  btnStyle: {
    marginLeft: rwp(20),
    marginTop: rhp(50),
    alignSelf: 'flex-start',
    padding: rhp(6),
    paddingLeft: 0,

    position: 'absolute',
  },
  backgroundImageContainer: {
    flex: 1,
    backgroundColor: colors.WHITE.defaultWhite,
    paddingHorizontal: rwp(20),
  },
  diffInputCon: {
    marginTop: rhp(10),
  },
  rememberMeViewCon: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: rhp(15),
    marginHorizontal: rwp(10),
  },
  ic_checkBox: {
    height: rhp(14),
    width: rwp(14),
  },
  rememberTxt: {
    fontFamily: fonts.SF_PRO_TEXT.Poppins.Regular,
    fontWeight: '500',
    fontSize: rfs(12),
    lineHeight: rhp(17),
    color: colors.BLACK.defaultBlack,
    marginLeft: rwp(11),
    flex: 1,
  },
  forgotTxt: {
    color: colors.GRAY.darkGray,
    fontFamily: fonts.SF_PRO_TEXT.Poppins.Medium,
    fontSize: rfs(12),
    lineHeight: rhp(17),
  },
  scannerCon: {
    marginTop: rhp(58),
    justifyContent: 'space-between',
    alignSelf: 'center',
    width: wp(40),
    flexDirection: 'row',
  },
  diffButtonStyle: {
    marginTop: rhp(15),
    justifyContent: 'center',
    alignItems: 'center',
  },
  SignUpBtnCon: {
    flexDirection: 'row',
    marginTop: rhp(16),
    justifyContent: 'center',
  },
  accountTxt: {
    fontFamily: fonts.SF_PRO_TEXT.Poppins.Light,
    fontWeight: '500',
    fontSize: rfs(12),
    lineHeight: rhp(17),
    color: colors.GRAY.textLightGray,
    marginRight: rwp(4),
  },
  signUpBtTxt: {
    color: colors.GREEN.lightGreen,
    fontWeight: '500',
    fontSize: rfs(13),
    lineHeight: rhp(17),
    textDecorationLine: 'underline',
  },
  upperContainer: {
    backgroundColor: 'green',
    width: '100%',
    height: rhp(244.59),
  },
  lowerContainer: {
    paddingHorizontal: rwp(20),
    flex: 1,
    marginTop: -rhp(34),
    borderTopStartRadius: rwp(30),
    borderTopEndRadius: rwp(30),
    backgroundColor: colors.WHITE.background,
  },
  titleText: {
    fontSize: rhp(35),
    marginTop: rhp(100),
    alignSelf: 'center',
    fontFamily: fonts.SF_PRO_TEXT.Poppins.SemiBold,
  },
  emailConatiner: {
    marginTop: rhp(10),
  },
  nameInput: {
    width: '45%',
  },
  continueWith: {
    width: '100%',
    resizeMode: 'contain',
    alignSelf: 'center',
    height: rhp(20),
    marginTop: rhp(12),
  },
  socialLogInContainer: {
    marginTop: rhp(23),
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: '15%',
  },
  logoContainer: {
    width: rwp(60),
    height: rhp(45),
    borderRadius: rhp(10),
    borderColor: colors.GRAY.textLightGray,
    borderWidth: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  socialLogoImage: {
    width: rwp(20),
    height: rhp(20),
    resizeMode: 'contain',
  },
  contentContainerStyle: {
    marginTop: rhp(40),
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: rwp(20),
  },
  accountDelete: {
    marginTop: rhp(10),
    alignSelf: 'center',
    textDecorationLine: 'underline',
    color: colors.GREEN.lightGreen,
    fontSize: rhp(11.5),
    fontFamily: fonts.SF_PRO_TEXT.Poppins.Regular,
  },
  inputContainer: {
    borderWidth: 0,
    //backgroundColor: colors.WHITE.defaultWhite,
    backgroundColor: '#f5fffa',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  emailCon: {
    borderWidth: 0,
    //backgroundColor: colors.WHITE.defaultWhite,
    backgroundColor: '#f5fffa',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  phoneInputContainer: {
    borderWidth: 0,
    //backgroundColor: colors.WHITE.defaultWhite,
    backgroundColor: '#f5fffa',
    marginTop: rhp(9),
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  userInfoText: {
    marginLeft: rwp(5),
    fontFamily: fonts.SF_PRO_TEXT.Poppins.Regular,
    fontSize: rfs(14),
    fontWeight: '600',
    lineHeight: rhp(20),
    color: colors.BLACK.defaultBlack,
  },
  diffPhoneInputCon: {
    marginTop: rhp(10),
    //zIndex: 1,
  },
  editableInputContainer: {
    borderWidth: 1.5,
    backgroundColor: colors.WHITE.defaultWhite,
    //backgroundColor: "#f5fffa",
    borderColor: colors.GRAY.lightGray,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  header: {
    backgroundColor: colors.GREEN.tintedGreen,
    width: '100%',
    height: rhp(141),
  },
  profileImageContainer: {
    height: rhp(115),
    width: rhp(115),
    backgroundColor: colors.GRAY.imageContainer,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    borderRadius: rhp(25),
    marginTop: -rhp(57.5),
    // overflow: 'hidden',
  },
  dummyProfile: {
    // flex: 1,
    height: rhp(115),
    borderRadius: rhp(25),
    width: rhp(115),
    resizeMode: 'contain',
  },
  plusViewCon: {
    position: 'absolute',
    bottom: -rhp(7),
    right: -rwp(7),
  },
  plusIcon: {
    height: rhp(30),
    width: rhp(30),
    resizeMode: 'contain',
  },
  editButton: {
    justifyContent: 'center',
    alignItems: 'center',
    width: '38%',
    height: rhp(40),
  },
  changePasswordButton: {
    justifyContent: 'center',
    alignItems: 'center',
    width: '38%',
    height: rhp(40),
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: colors.GREEN.lightGreen,
  },
  editButtonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    marginTop: rhp(35),
  },
  changePasswordText: {
    color: colors.GREEN.lightGreen,
    fontSize: rhp(12),
  },
  editButtonText: {
    fontSize: rhp(12),
  },
  disabledInput: {
    color: colors.BLACK.description,
  },
});

export default styles;
